import { ReactNode } from "react";

export interface PresetThemeType {
  name: string;
  primary: string;
  background: string;
  textPrimary?: string;
  textSecondary?: string;
  border?: string;
  borderHover?: string;
  borderFocus?: string;
  cardBackground: string;
  inputBackground?: string;
  dialogBackground?: string;
  dropdownBackground?: string;
  dropdownItemHover?: string;
  sidebarBackground?: string;
  sidebarItemHover?: string;
  sidebarItemFocus?: string;
  buttonBg?: string;
  buttonBgHover?: string;
  buttonText?: string;
  buttonBorder?: string;
  buttonBorderHover?: string;
  buttonSecondBg?: string;
  buttonSecondBgHover?: string;
  bookmarkItemBg?: string;
  bookmarkItemText?: string;
  drawerBackground?: string;
  clockGradientFrom?: string;
  clockGradientTo?: string;
  cardShadow?: string;
  dialogShadow?: string;
  dropdownShadow?: string;
  icon?: ReactNode;
  description?: string;
}

export const PRESET_THEMES: Record<"light" | "dark", PresetThemeType[]> = {
  light: [
    {
      name: "Default Light",
      primary: "#3686ff",
      background: "#ffffff",
      textPrimary: "#0f172a",
      textSecondary: "#475569",
      border: "#e2e8f0",
      borderHover: "#cbd5e1",
      borderFocus: "#cbd5e1",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#f8fafc",
      sidebarBackground: "#f9fafb",
      sidebarItemHover: "#f3f4f6",
      sidebarItemFocus: "#e5e7eb",
      buttonBg: "#3686ff",
      buttonBgHover: "#1d4ed8",
      buttonText: "#ffffff",
      buttonBorder: "#2563eb",
      buttonBorderHover: "#1e40af",
      buttonSecondBg: "#d4d4d4",
      buttonSecondBgHover: "#b6b6b6",
      bookmarkItemBg: "#f1f5f9",
      bookmarkItemText: "#0f172a",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#3686ff",
      clockGradientTo: "#1d4ed8",
    },
    {
      name: "Blue Light",
      primary: "#1e40af",
      background: "#eff6ff",
      textPrimary: "#1e3a8a",
      textSecondary: "#3730a3",
      border: "#bfdbfe",
      borderHover: "#93c5fd",
      cardBackground: "#ffffff",
      cardShadow: "rgba(30, 64, 175, 0.1)",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dialogShadow: "rgba(30, 64, 175, 0.15)",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#dbeafe",
      dropdownShadow: "rgba(30, 64, 175, 0.1)",
      sidebarBackground: "#dbeafe",
      sidebarItemHover: "#bfdbfe",
      sidebarItemFocus: "#93c5fd",
      buttonBg: "#1e40af",
      buttonBgHover: "#1e3a8a",
      buttonText: "#ffffff",
      buttonBorder: "#1d4ed8",
      buttonBorderHover: "#1e3a8a",
      buttonSecondBg: "#e0e7ff",
      buttonSecondBgHover: "#c7d2fe",
      bookmarkItemBg: "#dbeafe",
      bookmarkItemText: "#1e3a8a",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#1e40af",
      clockGradientTo: "#1e3a8a",
    },
    {
      name: "Emerald Light",
      primary: "#10b981",
      background: "#ecfdf5",
      textPrimary: "#064e3b",
      textSecondary: "#047857",
      border: "#a7f3d0",
      borderHover: "#6ee7b7",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#d1fae5",
      sidebarBackground: "#d1fae5",
      sidebarItemHover: "#a7f3d0",
      sidebarItemFocus: "#6ee7b7",
      buttonBg: "#10b981",
      buttonBgHover: "#059669",
      buttonText: "#ffffff",
      buttonBorder: "#059669",
      buttonBorderHover: "#047857",
      buttonSecondBg: "#d1fae5",
      buttonSecondBgHover: "#a7f3d0",
      bookmarkItemBg: "#d1fae5",
      bookmarkItemText: "#064e3b",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#10b981",
      clockGradientTo: "#059669",
    },
    {
      name: "Rose Light",
      primary: "#e11d48",
      background: "#fff1f2",
      textPrimary: "#881337",
      textSecondary: "#be185d",
      border: "#fbb6ce",
      borderHover: "#f9a8d4",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#fce7f3",
      sidebarBackground: "#fce7f3",
      sidebarItemHover: "#fbcfe8",
      sidebarItemFocus: "#f9a8d4",
      buttonBg: "#e11d48",
      buttonBgHover: "#be123c",
      buttonText: "#ffffff",
      buttonBorder: "#be123c",
      buttonBorderHover: "#9f1239",
      buttonSecondBg: "#fce7f3",
      buttonSecondBgHover: "#fbcfe8",
      bookmarkItemBg: "#fce7f3",
      bookmarkItemText: "#881337",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#e11d48",
      clockGradientTo: "#be123c",
    },
    {
      name: "Violet Light",
      primary: "#7c3aed",
      background: "#faf5ff",
      textPrimary: "#581c87",
      textSecondary: "#6b21a8",
      border: "#c4b5fd",
      borderHover: "#a78bfa",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#ede9fe",
      sidebarBackground: "#ede9fe",
      sidebarItemHover: "#ddd6fe",
      sidebarItemFocus: "#c4b5fd",
      buttonBg: "#7c3aed",
      buttonBgHover: "#6d28d9",
      buttonText: "#ffffff",
      buttonBorder: "#6d28d9",
      buttonBorderHover: "#5b21b6",
      buttonSecondBg: "#ede9fe",
      buttonSecondBgHover: "#ddd6fe",
      bookmarkItemBg: "#ede9fe",
      bookmarkItemText: "#581c87",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#7c3aed",
      clockGradientTo: "#6d28d9",
    },
    {
      name: "Orange Light",
      primary: "#ea580c",
      background: "#fff7ed",
      textPrimary: "#9a3412",
      textSecondary: "#c2410c",
      border: "#fed7aa",
      borderHover: "#fdba74",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#ffedd5",
      sidebarBackground: "#ffedd5",
      sidebarItemHover: "#fed7aa",
      sidebarItemFocus: "#fdba74",
      buttonBg: "#ea580c",
      buttonBgHover: "#dc2626",
      buttonText: "#ffffff",
      buttonBorder: "#dc2626",
      buttonBorderHover: "#b91c1c",
      buttonSecondBg: "#ffedd5",
      buttonSecondBgHover: "#fed7aa",
      bookmarkItemBg: "#ffedd5",
      bookmarkItemText: "#9a3412",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#ea580c",
      clockGradientTo: "#dc2626",
    },
    {
      name: "Teal Light",
      primary: "#0d9488",
      background: "#f0fdfa",
      textPrimary: "#134e4a",
      textSecondary: "#0f766e",
      border: "#99f6e4",
      borderHover: "#5eead4",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#ccfbf1",
      sidebarBackground: "#ccfbf1",
      sidebarItemHover: "#99f6e4",
      sidebarItemFocus: "#5eead4",
      buttonBg: "#0d9488",
      buttonBgHover: "#0f766e",
      buttonText: "#ffffff",
      buttonBorder: "#0f766e",
      buttonBorderHover: "#134e4a",
      buttonSecondBg: "#ccfbf1",
      buttonSecondBgHover: "#99f6e4",
      bookmarkItemBg: "#ccfbf1",
      bookmarkItemText: "#134e4a",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#0d9488",
      clockGradientTo: "#0f766e",
    },
    {
      name: "Pink Light",
      primary: "#db2777",
      background: "#fdf2f8",
      textPrimary: "#831843",
      textSecondary: "#be185d",
      border: "#f3e8ff",
      borderHover: "#e879f9",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#fce7f3",
      sidebarBackground: "#fce7f3",
      sidebarItemHover: "#fbcfe8",
      sidebarItemFocus: "#f9a8d4",
      buttonBg: "#db2777",
      buttonBgHover: "#be185d",
      buttonText: "#ffffff",
      buttonBorder: "#be185d",
      buttonBorderHover: "#9d174d",
      buttonSecondBg: "#fce7f3",
      buttonSecondBgHover: "#fbcfe8",
      bookmarkItemBg: "#fce7f3",
      bookmarkItemText: "#831843",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#db2777",
      clockGradientTo: "#be185d",
    },
    {
      name: "Indigo Light",
      primary: "#4f46e5",
      background: "#eef2ff",
      textPrimary: "#3730a3",
      textSecondary: "#4338ca",
      border: "#c7d2fe",
      borderHover: "#a5b4fc",
      borderFocus: "#a5b4fc",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#e0e7ff",
      sidebarBackground: "#e0e7ff",
      sidebarItemHover: "#c7d2fe",
      sidebarItemFocus: "#a5b4fc",
      buttonBg: "#4f46e5",
      buttonBgHover: "#4338ca",
      buttonText: "#ffffff",
      buttonBorder: "#4338ca",
      buttonBorderHover: "#3730a3",
      buttonSecondBg: "#e0e7ff",
      buttonSecondBgHover: "#c7d2fe",
      bookmarkItemBg: "#e0e7ff",
      bookmarkItemText: "#3730a3",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#4f46e5",
      clockGradientTo: "#4338ca",
    },
    {
      name: "Cyan Light",
      primary: "#0891b2",
      background: "#ecfeff",
      textPrimary: "#164e63",
      textSecondary: "#0e7490",
      border: "#a5f3fc",
      borderHover: "#67e8f9",
      cardBackground: "#ffffff",
      inputBackground: "#ffffff",
      dialogBackground: "#ffffff",
      dropdownBackground: "#ffffff",
      dropdownItemHover: "#cffafe",
      sidebarBackground: "#cffafe",
      sidebarItemHover: "#a5f3fc",
      sidebarItemFocus: "#67e8f9",
      buttonBg: "#0891b2",
      buttonBgHover: "#0e7490",
      buttonText: "#ffffff",
      buttonBorder: "#0e7490",
      buttonBorderHover: "#155e75",
      buttonSecondBg: "#cffafe",
      buttonSecondBgHover: "#a5f3fc",
      bookmarkItemBg: "#cffafe",
      bookmarkItemText: "#164e63",
      drawerBackground: "#ffffff",
      clockGradientFrom: "#0891b2",
      clockGradientTo: "#0e7490",
    },
  ],
  dark: [
    {
      name: "Default Dark",
      primary: "#3686ff",
      background: "#0a0a0a",
      textPrimary: "#ececec",
      textSecondary: "#a8a8a8",
      border: "#353535",
      borderHover: "#418dfe",
      borderFocus: "#418dfe",
      cardBackground: "#242424",
      inputBackground: "#1e1e1e",
      dialogBackground: "#1e1e1e",
      dropdownBackground: "#1e1e1e",
      dropdownItemHover: "#2d2d2d",
      sidebarBackground: "#131313",
      sidebarItemHover: "#1e1e1e",
      sidebarItemFocus: "#333333",
      buttonBg: "#3686ff",
      buttonBgHover: "#418dfe",
      buttonText: "#ffffff",
      buttonBorder: "#418dfe",
      buttonBorderHover: "#5aa3ff",
      buttonSecondBg: "#1e1e1e",
      buttonSecondBgHover: "#343434",
      bookmarkItemBg: "#1e293b",
      bookmarkItemText: "#e2e8f0",
      drawerBackground: "#1e1e1e",
      clockGradientFrom: "#3686ff",
      clockGradientTo: "#418dfe",
    },
    // {
    //     name: "Deep Purple",
    //     primary: "#8b5cf6",
    //     background: "#0f172a",
    //     textPrimary: "#e2e8f0",
    //     textSecondary: "#94a3b8",
    //     border: "#4c1d95",
    //     borderHover: "#7c3aed",
    //     cardBackground: "#1e293b",
    //     inputBackground: "#334155",
    //     dialogBackground: "#1e293b",
    //     dropdownBackground: "#334155",
    //     dropdownItemHover: "#475569",
    //     sidebarBackground: "#1a1b3a",
    //     sidebarItemHover: "#312e81",
    //     sidebarItemFocus: "#4c1d95",
    //     buttonBg: "#8b5cf6",
    //     buttonBgHover: "#7c3aed",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#7c3aed",
    //     buttonBorderHover: "#6d28d9",
    //     buttonSecondBg: "#334155",
    //     buttonSecondBgHover: "#475569",
    //     bookmarkItemBg: "#312e81",
    //     bookmarkItemText: "#e2e8f0",
    //     drawerBackground: "#1e293b",
    //     clockGradientFrom: "#8b5cf6",
    //     clockGradientTo: "#7c3aed",
    // },
    // {
    //     name: "Amber Dark",
    //     primary: "#f59e0b",
    //     background: "#1c1917",
    //     textPrimary: "#fbbf24",
    //     textSecondary: "#d97706",
    //     border: "#78350f",
    //     borderHover: "#f59e0b",
    //     cardBackground: "#292524",
    //     inputBackground: "#44403c",
    //     dialogBackground: "#292524",
    //     dropdownBackground: "#44403c",
    //     dropdownItemHover: "#57534e",
    //     sidebarBackground: "#2a211d",
    //     sidebarItemHover: "#44403c",
    //     sidebarItemFocus: "#57534e",
    //     buttonBg: "#f59e0b",
    //     buttonBgHover: "#d97706",
    //     buttonText: "#1c1917",
    //     buttonBorder: "#d97706",
    //     buttonBorderHover: "#b45309",
    //     buttonSecondBg: "#44403c",
    //     buttonSecondBgHover: "#57534e",
    //     bookmarkItemBg: "#451a03",
    //     bookmarkItemText: "#fbbf24",
    //     drawerBackground: "#292524",
    //     clockGradientFrom: "#f59e0b",
    //     clockGradientTo: "#d97706",
    // },
    // {
    //     name: "Crimson Dark",
    //     primary: "#ef4444",
    //     background: "#0c0a09",
    //     textPrimary: "#fca5a5",
    //     textSecondary: "#f87171",
    //     border: "#7f1d1d",
    //     borderHover: "#ef4444",
    //     cardBackground: "#1c1917",
    //     inputBackground: "#44403c",
    //     dialogBackground: "#1c1917",
    //     dropdownBackground: "#44403c",
    //     dropdownItemHover: "#57534e",
    //     sidebarBackground: "#2b1a1a",
    //     sidebarItemHover: "#44403c",
    //     sidebarItemFocus: "#57534e",
    //     buttonBg: "#ef4444",
    //     buttonBgHover: "#dc2626",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#dc2626",
    //     buttonBorderHover: "#b91c1c",
    //     buttonSecondBg: "#44403c",
    //     buttonSecondBgHover: "#57534e",
    //     bookmarkItemBg: "#7f1d1d",
    //     bookmarkItemText: "#fca5a5",
    //     drawerBackground: "#1c1917",
    //     clockGradientFrom: "#ef4444",
    //     clockGradientTo: "#dc2626",
    // },
    // {
    //     name: "Emerald Dark",
    //     primary: "#10b981",
    //     background: "#0f1419",
    //     textPrimary: "#6ee7b7",
    //     textSecondary: "#34d399",
    //     border: "#064e3b",
    //     borderHover: "#10b981",
    //     cardBackground: "#1f2937",
    //     inputBackground: "#374151",
    //     dialogBackground: "#1f2937",
    //     dropdownBackground: "#374151",
    //     dropdownItemHover: "#4b5563",
    //     sidebarBackground: "#12231d",
    //     sidebarItemHover: "#1f2937",
    //     sidebarItemFocus: "#374151",
    //     buttonBg: "#10b981",
    //     buttonBgHover: "#059669",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#059669",
    //     buttonBorderHover: "#047857",
    //     buttonSecondBg: "#374151",
    //     buttonSecondBgHover: "#4b5563",
    //     bookmarkItemBg: "#064e3b",
    //     bookmarkItemText: "#6ee7b7",
    //     drawerBackground: "#1f2937",
    //     clockGradientFrom: "#10b981",
    //     clockGradientTo: "#059669",
    // },
    // {
    //     name: "Ocean Dark",
    //     primary: "#06b6d4",
    //     background: "#082f49",
    //     textPrimary: "#67e8f9",
    //     textSecondary: "#22d3ee",
    //     border: "#164e63",
    //     borderHover: "#06b6d4",
    //     cardBackground: "#0c4a6e",
    //     inputBackground: "#155e75",
    //     dialogBackground: "#0c4a6e",
    //     dropdownBackground: "#155e75",
    //     dropdownItemHover: "#0e7490",
    //     sidebarBackground: "#063c57",
    //     sidebarItemHover: "#0c4a6e",
    //     sidebarItemFocus: "#155e75",
    //     buttonBg: "#06b6d4",
    //     buttonBgHover: "#0891b2",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#0891b2",
    //     buttonBorderHover: "#0e7490",
    //     buttonSecondBg: "#155e75",
    //     buttonSecondBgHover: "#0e7490",
    //     bookmarkItemBg: "#164e63",
    //     bookmarkItemText: "#67e8f9",
    //     drawerBackground: "#0c4a6e",
    //     clockGradientFrom: "#06b6d4",
    //     clockGradientTo: "#0891b2",
    // },
    // {
    //     name: "Forest Dark",
    //     primary: "#22c55e",
    //     background: "#0f172a",
    //     textPrimary: "#86efac",
    //     textSecondary: "#4ade80",
    //     border: "#15803d",
    //     borderHover: "#22c55e",
    //     cardBackground: "#1e293b",
    //     inputBackground: "#334155",
    //     dialogBackground: "#1e293b",
    //     dropdownBackground: "#334155",
    //     dropdownItemHover: "#475569",
    //     sidebarBackground: "#122a1b",
    //     sidebarItemHover: "#1e293b",
    //     sidebarItemFocus: "#334155",
    //     buttonBg: "#22c55e",
    //     buttonBgHover: "#16a34a",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#16a34a",
    //     buttonBorderHover: "#15803d",
    //     buttonSecondBg: "#334155",
    //     buttonSecondBgHover: "#475569",
    //     bookmarkItemBg: "#15803d",
    //     bookmarkItemText: "#86efac",
    //     drawerBackground: "#1e293b",
    //     clockGradientFrom: "#22c55e",
    //     clockGradientTo: "#16a34a",
    // },
    // {
    //     name: "Sunset Dark",
    //     primary: "#f97316",
    //     background: "#1a202c",
    //     textPrimary: "#fdba74",
    //     textSecondary: "#fb923c",
    //     border: "#9a3412",
    //     borderHover: "#f97316",
    //     cardBackground: "#2d3748",
    //     inputBackground: "#4a5568",
    //     dialogBackground: "#2d3748",
    //     dropdownBackground: "#4a5568",
    //     dropdownItemHover: "#718096",
    //     sidebarBackground: "#32261e",
    //     sidebarItemHover: "#2d3748",
    //     sidebarItemFocus: "#4a5568",
    //     buttonBg: "#f97316",
    //     buttonBgHover: "#ea580c",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#ea580c",
    //     buttonBorderHover: "#c2410c",
    //     buttonSecondBg: "#4a5568",
    //     buttonSecondBgHover: "#718096",
    //     bookmarkItemBg: "#9a3412",
    //     bookmarkItemText: "#fdba74",
    //     drawerBackground: "#2d3748",
    //     clockGradientFrom: "#f97316",
    //     clockGradientTo: "#ea580c",
    // },
    // {
    //     name: "Lavender Dark",
    //     primary: "#a855f7",
    //     background: "#1e1b4b",
    //     textPrimary: "#c4b5fd",
    //     textSecondary: "#a78bfa",
    //     border: "#581c87",
    //     borderHover: "#a855f7",
    //     cardBackground: "#312e81",
    //     inputBackground: "#4338ca",
    //     dialogBackground: "#312e81",
    //     dropdownBackground: "#4338ca",
    //     dropdownItemHover: "#4f46e5",
    //     sidebarBackground: "#27235a",
    //     sidebarItemHover: "#312e81",
    //     sidebarItemFocus: "#4338ca",
    //     buttonBg: "#a855f7",
    //     buttonBgHover: "#9333ea",
    //     buttonText: "#ffffff",
    //     buttonBorder: "#9333ea",
    //     buttonBorderHover: "#7c3aed",
    //     buttonSecondBg: "#4338ca",
    //     buttonSecondBgHover: "#4f46e5",
    //     bookmarkItemBg: "#581c87",
    //     bookmarkItemText: "#c4b5fd",
    //     drawerBackground: "#312e81",
    //     clockGradientFrom: "#a855f7",
    //     clockGradientTo: "#9333ea",
    // },
    {
      name: "Midnight Dark",
      primary: "#6366f1",
      background: "#020617",
      textPrimary: "#e2e8f0",
      textSecondary: "#94a3b8",
      border: "#1e293b",
      borderHover: "#6366f1",
      borderFocus: "#6366f1",
      cardBackground: "#0f172a",
      inputBackground: "#1e293b",
      dialogBackground: "#0f172a",
      dropdownBackground: "#1e293b",
      dropdownItemHover: "#334155",
      sidebarBackground: "#0b0e2a",
      sidebarItemHover: "#0f172a",
      sidebarItemFocus: "#1e293b",
      buttonBg: "#6366f1",
      buttonBgHover: "#4f46e5",
      buttonText: "#ffffff",
      buttonBorder: "#4f46e5",
      buttonBorderHover: "#4338ca",
      buttonSecondBg: "#1e293b",
      buttonSecondBgHover: "#334155",
      bookmarkItemBg: "#1e293b",
      bookmarkItemText: "#e2e8f0",
      drawerBackground: "#0f172a",
      clockGradientFrom: "#6366f1",
      clockGradientTo: "#4f46e5",
    },
  ],
};
